# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Blog"
  url = "post"
  weight = 10

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 20

[[main]]
  name = "Awards"
  url = "#accomplishments"
  weight = 30

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 40

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

[[main]]
  name = "Resume"
  url = "https://www.dropbox.com/scl/fi/uncglgbosfwdwrfxfy1g4/Eliany_Perez_cv.docx?rlkey=p0t4bqpbnj150wrgt78113gzm&dl=0"
  weight = 70
