# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
#  - name: Talks
#    url: '#talks'
#    weight: 30
  - name: Posts
    url: '#posts'
    weight: 20
  - name: Featured
    url: '#featured'
    weight: 30
  - name: Publications
    url: '#publications'
    weight: 40
  - name: Portfolio
    url: '#portfolio'
    weight: 50
    content: |
      <iframe src="https://www.beautiful.ai/player/-O5hmunN0yY1fiwYYl2x" 
              frameborder="0" 
              width="100%" 
              height="500" 
              allowfullscreen>
      </iframe>
  - name: CV
    url: uploads/Perez_CV.pdf
    weight: 80
 # - name: Skills
  #  url: '#skills'
  #  weight: 60
  - name: Contact
    url: '#contact'
    weight: 70
#  - name: Slides
#    url: '#slides'
#    weight: 60
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.

#link a file with posters
#  - name: Posters
#    url: uploads/posters.pdf
#    weight: 70
